Keywords:
  - "jdbc:"
  - redis
  - mysql
  - pgsql
  - postgresql
  - oracle
  - oss.
  - oss.accessKey
  - oss.secretKey
  - secretKey
  - accessKey
  - ak
  - sk
  - mongondb
  - secret
  - password
  - username
  - pass
  - user
  - pwd
  - mail
  - smtp
  - token
  - datasource
  - accessKeyId
  - accessKeySecret
  - sms
  - access
  - mssql
  - sqlserver
  - aliyun
  - oss
  - kingbase8
  - kingbase
  - SQLite
  - Neo4j
